version: "3.7"

services:
  pg:
    image: postgres:alpine
    environment:
      POSTGRES_DB: crawlee
      POSTGRES_USER: crawlee
      POSTGRES_PASSWORD: secret
      TZ: UTC
      PGTZ: UTC
    ports:
      - 5432:5432
    volumes:
      - pgdata1:/var/lib/postgresql/data


volumes:
  pgdata1:
